Book length limit
wolox-training/ff-rails pull request #25
Opened 2020-02-11 14:13 UTC by ffasitella

### Summary

- Generated a migration to limit the length of the book titles to 25.
- For the existing books, it truncated their titles and added "..." at the end.

### Trello card

https://trello.com/c/vOR570sA/43-migraciones-opcional

2020-02-11 14:42 UTC, edkajimenez approved these changes

2020-02-11 14:42 UTC, edkajimenez commented on db/migrate/20200211134024_add_book_title_size_limit.rb
> +  def truncate_book_titles
Uhmm I think in here it can be the same comment that I let on the prev PR, it will be more readable (If that word exists) to have this being called `book` instead of `b` so you can always have present that you are getting info from a book and don't have to remember what `b` means. I don't mark this as mandatory since this is just a suggestion as a style thing.

2020-02-11 15:21 UTC, marcegl91 requested changes

2020-02-11 15:21 UTC, marcegl91 commented on db/migrate/20200211134024_add_book_title_size_limit.rb
> +    Book.all.each do |b|
This is ok, but bear in mind that you could filter which books have a length greater than 25 and modify only those. In a production environment this would be necessary instead of visiting each Book in the database.

Also, for this PR is ok that you use DML (ie, you modify the data in the migration) but I strongly discourage from using this in a real project. It should be better to do the modification of the schema in the migration, and after that create and run a Rake task where you do the processing of the data. This mistake is really common in Wolox projects and eventually creates lots of troubles. If you have a little time to spare, I strongly recommend you to read this article:

https://thoughtbot.com/blog/data-migrations-in-rails

2020-02-17 15:59 UTC, marcegl91 submitted a review, later dismissed
Great work! :tada:

2020-03-16 15:32 UTC, edkajimenez submitted a review, later dismissed

2020-03-16 15:40 UTC, marcegl91 approved these changes

2020-03-16 15:41 UTC, merged