Adding book seeds
wolox-training/ff-rails pull request #26
Opened 2020-02-11 14:31 UTC by ffasitella

### Summary

- Adding seeds.rb to create 50.000 books whit the command `rake db:seed` 

### Trello card

https://trello.com/c/ikI0rd9M/42-seeds-opcional

2020-02-11 15:38 UTC, marcegl91 commented on db/seeds.rb
> +50000.times { Book.create(
Although rubocop does not check this file by default, you can run rubocop here and it will return lots of warnings of style :) .

2020-02-11 15:39 UTC, marcegl91 commented on db/seeds.rb
> +  title: Faker::Book.title,
In the previous PR, you limited the number of characters that a title can have. What would happen if Faker::Book returns a title that has more than 25 characters?

2020-02-17 16:02 UTC, marcegl91 requested changes

2020-02-17 16:02 UTC, marcegl91 commented on db/seeds.rb
> +require 'faker'
Why do you need this require?

2020-03-03 15:13 UTC, marcegl91 submitted a review, later dismissed

2020-03-16 15:33 UTC, edkajimenez submitted a review, later dismissed

2020-03-16 15:42 UTC, marcegl91 approved these changes

2020-03-16 15:42 UTC, merged